<script>
      export default {
            color: {
                  lightBlueTea: "gradient-45deg-light-blue-teal",
                  lightBlueTealShadow: "gradient-45deg-light-blue-teal gradient-shadow",
                  indigoLightBlue: "gradient-45deg-indigo-light-blue",
                  indigoLightBlueShadow: "gradient-45deg-indigo-light-blue gradient-shadow",
                  lightBlueIndigo: "gradient-45deg-light-blue-indigo",
                  lightBlueIndigoShadow: "gradient-45deg-light-blue-indigo gradient-shadow",
                  yellowGreen: "gradient-45deg-yellow-green",
                  yellowGreenShadow: "gradient-45deg-yellow-green gradient-shadow",
                  orangeDeepOrange: "gradient-45deg-orange-deep-orange",
                  orangeDeepOrangeShadow: "gradient-45deg-orange-deep-orange gradient-shadow",
                  deepPurplePurple: "gradient-45deg-deep-purple-purple",
                  deepPurplePurpleShadow: "gradient-45deg-deep-purple-purple gradient-shadow",
                  redPink: "gradient-45deg-red-pink",
                  redPinkShadow: "gradient-45deg-red-pink gradient-shadow",
                  lightGreenAmber: "gradient-45deg-light-green-amber",
                  lightGreenAmberShadow: "gradient-45deg-light-green-amber gradient-shadow",
                  amberAmber: "gradient-45deg-amber-amber",
                  amberAmberShadow: "gradient-45deg-amber-amber gradient-shadow",
                  purplePink: "gradient-45deg-purple-pink",
                  purplePinkShadow: "gradient-45deg-purple-pink gradient-shadow",
                  indigoLightBlue: "gradient-45deg-indigo-light-blue",
                  indigoLightBlueShadow: "gradient-45deg-indigo-light-blue gradient-shadow",
                  tealCyan: "gradient-45deg-teal-cyan",
                  tealCyanShadow: "gradient-45deg-teal-cyan gradient-shadow",
                  blueGreyBlueGrey: "gradient-45deg-blue-grey-blue-grey",
                  blueGreyBlueGreyShadow: "gradient-45deg-blue-grey-blue-grey gradient-shadow",
                  cyanLightGreen: "gradient-45deg-cyan-light-green",
                  cyanLightGreenShadow: "gradient-45deg-cyan-light-green gradient-shadow",
                  orangeAmber: "gradient-45deg-orange-amber",
                  orangeAmberShadow: "gradient-45deg-orange-amber gradient-shadow",
                  indigoBlue: "gradient-45deg-indigo-blue",
                  indigoBlueShadow: "gradient-45deg-indigo-blue gradient-shadow",
                  brownBrown: "gradient-45deg-brown-brown",
                  brownBrownShadow: "gradient-45deg-brown-brown gradient-shadow",
                  blueGreyBlue: "gradient-45deg-blue-grey-blue",
                  blueGreyBlueShadow: "gradient-45deg-blue-grey-blue gradient-shadow",
                  purpleDeepOrange: "gradient-45deg-purple-deep-orange",
                  purpleDeepOrangeShadow: "gradient-45deg-purple-deep-orange gradient-shadow",
                  greenTeal: "gradient-45deg-green-teal",
                  greenTealShadow: "gradient-45deg-green-teal gradient-shadow",
                  purpleLightBlue: "gradient-45deg-purple-light-blue",
                  purpleLightBlueShadow: "gradient-45deg-purple-light-blue gradient-shadow",
                  cyanCyan: "gradient-45deg-cyan-cyan",
                  cyanCyanShadow: "gradient-45deg-cyan-cyan gradient-shadow",
                  yellowTeal: "gradient-45deg-yellow-teal",
                  yellowTealShadow: "gradient-45deg-yellow-teal gradient-shadow",
                  purpleDeepPurple: "gradient-45deg-purple-deep-purple",
                  purpleDeepPurpleShadow: "gradient-45deg-purple-deep-purple gradient-shadow",
                  cyanLightGreen: "gradient-45deg-cyan-light-green",
                  cyanLightGreenShadow: "gradient-45deg-cyan-light-green gradient-shadow",
                  purpleAmber: "gradient-45deg-purple-amber",
                  purpleAmberShadow: "gradient-45deg-purple-amber gradient-shadow",
                  indigoPurple: "gradient-45deg-indigo-purple",
                  indigoPurpleShadow: "gradient-45deg-indigo-purple gradient-shadow",
                  deepPurpleBlue: "gradient-45deg-deep-purple-blue",
                  deepPurpleBlueShadow: "gradient-45deg-deep-purple-blue gradient-shadow",
                  deepOrangeOrange: "gradient-45deg-deep-orange-orange",
                  deepOrangeOrangeShadow: "gradient-45deg-deep-orange-orange gradient-shadow",
                  lightBlueCyan: "gradient-45deg-light-blue-cyan",
                  lightBlueCyanShadow: "gradient-45deg-light-blue-cyan gradient-shadow",
                  blueIndigo: "gradient-45deg-blue-indigo",
                  blueIndigoShadow: "gradient-45deg-blue-indigo gradient-shadow",
                  semiDark: "gradient-45deg-semi-dark",
                  semiDarkShadow: "gradient-45deg-semi-dark gradient-shadow",
            },
            // navColor: this.color.lightBlueTea,
      };
</script>

