<?php 
$rules  = [
	['class' => 'yii\rest\UrlRule', 'controller' => 'attachment'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'attachment-access'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'attachment-metatag'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'attachment-metatag-keylist'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'branch'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'company'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'company-pic'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'company-role'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'company-role-assignment'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'efies'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'efies-status'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'fe-service'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'fe-service-status'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'fe-service-type'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'fe-type'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'level'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'location'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'migration'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'notified'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'order'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'order-item'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'order-item-type'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'profile'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'service-reason'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'setting'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'site'],
	['class' => 'yii\rest\UrlRule', 'controller' => 'user'],
];
